# **NumPy Arrays — সম্পূর্ণ নোটস**

**NumPy কী?**

**NumPy (Numerical Python)** হলো পাইথনের সবচেয়ে গুরুত্বপূর্ণ লাইব্রেরি যা সংখ্যাভিত্তিক গণনার জন্য ব্যবহার করা হয়। ডেটা সায়েন্স এবং মেশিন লার্নিংয়ে এটি ছাড়া কাজ করা প্রায় অসম্ভব।

**কেন NumPy ব্যবহার করি?**

সাধারণ পাইথন লিস্টের চেয়ে NumPy array অনেক দ্রুত কাজ করে
একসাথে অনেক সংখ্যার উপর গাণিতিক অপারেশন করা যায়
কম কোডে বেশি কাজ হয়
Pandas, Matplotlib, Scikit-learn সহ সব বড় লাইব্রেরি ভেতরে ভেতরে NumPy ব্যবহার করে

In [1]:
import numpy as np

**import numpy as np** মানে হলো numpy লাইব্রেরিকে **np** নামে ডাকবো — এটা সবার কাছে প্রচলিত convention।

# **১. Basic Array Creation (অ্যারে তৈরি করা)**



**Array কী?**
Array হলো একই ধরনের ডেটার একটি সংগঠিত সংগ্রহ। পাইথন লিস্টের মতোই, কিন্তু অনেক বেশি শক্তিশালী। NumPy array কে বলা হয় **ndarray (n-dimensional array)**।

**লিস্ট বনাম Array:**

1. পাইথন লিস্টে বিভিন্ন ধরনের ডেটা রাখা যায় (int, string একসাথে)
2. NumPy array তে সব উপাদান একই ডেটা টাইপ হতে হয়
3. Array তে গণিত করা যায়, লিস্টে সরাসরি যায় না

In [2]:
# এক মাত্রিক (1D) array তৈরি
arr = np.array([1,2,3,4])
arr
# output: array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
# পাইথন লিস্ট থেকে array তৈরি
# লক্ষ্য করো — লিস্টে int আর float একসাথে আছে
a = [1, 2, 3.5]
a
# output: [1, 2, 3.5]

[1, 2, 3.5]

In [4]:
# লিস্টকে array তে রূপান্তর করলে সব উপাদান float হয়ে যায়
# কারণ array তে সব উপাদান একই টাইপ হতে হয়, তাই সবচেয়ে বড় টাইপ (float) নেয়
np.array(a)
# output: array([1. , 2. , 3.5])

array([1. , 2. , 3.5])

In [5]:
# দ্বিমাত্রিক (2D) array তৈরি — list of lists দিয়ে
l = [[1,2,3],[4,5,6],[7,8,9]]
l
# output: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
# 2D array — matrix এর মতো দেখতে (সারি ও কলাম আছে)
np.array(l)
# output:
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **২. Array Generation Functions** (ফাংশন দিয়ে array তৈরি)

হাতে হাতে array না লিখে NumPy এর built-in ফাংশন দিয়ে দ্রুত array তৈরি করা যায়।

**np.arange()** — নির্দিষ্ট range এ array

**Syntax:** `np.arange(start, stop, step)`


**start** → কোথা থেকে শুরু

**stop** → কোথায় শেষ (এই মান অন্তর্ভুক্ত হয় না)

**step** → কত করে বাড়বে

In [7]:
arr = np.arange(1, 11, 2)
arr
# output: array([1, 3, 5, 7, 9])
# 1 থেকে শুরু, 11 এর আগে শেষ, 2 করে বাড়ছে → শুধু বিজোড় সংখ্যা

array([1, 3, 5, 7, 9])

**np.zeros()** — সব শূন্য দিয়ে array

**Syntax:** `np.zeros((rows, cols))`

যখন একটা খালি array দরকার হয় প্রাথমিক অবস্থায়, তখন zeros ব্যবহার করা হয়। মেশিন লার্নিংয়ে weight initialize করতে কাজে লাগে।

In [8]:
arr = np.zeros((4, 8))
arr
# output: 4 সারি, 8 কলামের সব 0.0 দিয়ে ভরা array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

**np.ones()** — সব এক দিয়ে array

**Syntax:** `np.ones((rows, cols))`

In [9]:
arr = np.ones((6, 6))
arr
# output: 6x6 array, সব মান 1.0

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**np.linspace() — সমান দূরত্বে ভাগ করা array**

**Syntax:** `np.linspace(start, stop, num)`

**start** → শুরুর মান

**stop** → শেষের মান (এটা অন্তর্ভুক্ত হয়, arange এর মতো না)

**num** → মোট কতটি সংখ্যা চাই

arange এর সাথে পার্থক্য → arange তে step দাও, linspace তে মোট সংখ্যার count দাও।

In [10]:
arr = np.linspace(0, 1, 100)
arr
# output: 0 থেকে 1 পর্যন্ত সমান দূরত্বে 100টি সংখ্যা

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# **৩. Random Generation Functions (এলোমেলো সংখ্যা তৈরি)**

ডেটা সায়েন্সে প্র্যাকটিসের জন্য নমুনা ডেটা তৈরি করতে বা মেশিন লার্নিং মডেলে random initialization করতে এগুলো ব্যবহার হয়।

**np.random.rand() — 0 থেকে 1 এর মধ্যে random**

**বৈশিষ্ট্য:** Uniform distribution — সব মান সমান সম্ভাবনায় আসে

In [11]:
np.random.rand(10)
# output: 0 থেকে 1 এর মধ্যে 10টি এলোমেলো দশমিক সংখ্যা
# যেমন: array([0.58, 0.17, 0.13, ...])

array([0.76876859, 0.35976696, 0.1539345 , 0.02405336, 0.12012712,
       0.47575131, 0.16513122, 0.03577164, 0.14574874, 0.13169858])

**np.random.randn() — Normal distribution থেকে random**

**বৈশিষ্ট্য:** Standard Normal distribution — গড় 0, বিচ্যুতি 1। তাই ঋণাত্মক মানও আসতে পারে। বাস্তব জীবনের বেশিরভাগ ডেটা এই বিতরণ অনুসরণ করে।

In [13]:
np.random.randn(10)
# output: ধনাত্মক ও ঋণাত্মক দশমিক সংখ্যা, গড় প্রায় 0 এর কাছাকাছি
# যেমন: array([0.75, -1.89, -0.83, ...])

array([ 0.04728639, -0.06925599, -0.50016641, -0.86673086, -0.18733867,
       -0.63778096,  1.30192714, -0.15048664,  0.50571277,  1.57185896])

**np.random.randint() — নির্দিষ্ট range এ random পূর্ণসংখ্যা**

**Syntax:** `np.random.randint(low, high, size)`

**low** → সর্বনিম্ন মান (অন্তর্ভুক্ত)

**high** → সর্বোচ্চ মান (অন্তর্ভুক্ত নয়)

**size** → কতটি সংখ্যা চাই

In [14]:
np.random.randint(10, 20, 10)
# output: 10 থেকে 19 এর মধ্যে 10টি এলোমেলো পূর্ণসংখ্যা
# যেমন: array([17, 13, 19, 16, ...])

array([17, 19, 16, 19, 18, 15, 13, 10, 16, 11])

# **৪. Array Attributes (array এর বৈশিষ্ট্য)**

Array তৈরির পর সেটা সম্পর্কে তথ্য জানতে attributes ব্যবহার করি। এগুলো ফাংশন নয়, তাই শেষে () লাগে না।

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**.shape — array এর আকার**

কতটি সারি (row) এবং কতটি কলাম (column) আছে তা tuple আকারে দেয়।

In [16]:
arr.shape
# output: (3, 3) → 3টি সারি, 3টি কলাম

(3, 3)

**.size — মোট উপাদানের সংখ্যা**

In [17]:
arr.size
# output: 9 → মোট 9টি উপাদান (3×3)

9

**.dtype — উপাদানগুলোর ডেটা টাইপ**

In [18]:
arr.dtype
# output: dtype('int64') → সব উপাদান 64-bit integer

dtype('int64')

**int64 কেন?** NumPy ডিফল্টভাবে 64-bit integer ব্যবহার করে কারণ এতে অনেক বড় সংখ্যা ধরা যায়। float হলে float64 দেখাতো।

# **৫. Array Methods (array এর উপর গণনা)**

এগুলো **ফাংশন/মেথড**, তাই শেষে `()` লাগে।

In [19]:
arr
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**.min() এবং .max() — সর্বনিম্ন ও সর্বোচ্চ**

In [21]:
arr.min()
# output: 1 → পুরো array তে সবচেয়ে ছোট মান

np.int64(1)

In [22]:
arr.max()
# output: 9 → পুরো array তে সবচেয়ে বড় মান

np.int64(9)

**.sum() — সব উপাদানের যোগফল**

In [23]:
arr.sum()
# output: 45 → 1+2+3+...+9 = 45

np.int64(45)

**Axis দিয়ে sum — দিক নির্ধারণ করা:**

**axis=0** → কলাম বরাবর যোগ (উপর থেকে নিচে)
**axis=1** → সারি বরাবর যোগ (বাম থেকে ডানে)

In [24]:
np.sum(arr, axis=1)
# output: array([ 6, 15, 24])
# প্রথম সারি: 1+2+3 = 6
# দ্বিতীয় সারি: 4+5+6 = 15
# তৃতীয় সারি: 7+8+9 = 24

array([ 6, 15, 24])

In [25]:
np.sum(arr, axis=0)


array([12, 15, 18])

**.mean() — গড় (Average)**

In [26]:
arr.mean()
# output: 5.0 → (1+2+...+9) / 9 = 5.0

np.float64(5.0)

**.std() — Standard Deviation (আদর্শ বিচ্যুতি)**

ডেটা গড় থেকে কতটা ছড়িয়ে আছে তা বোঝায়। মান কম হলে ডেটা গড়ের কাছাকাছি, বেশি হলে ডেটা বেশি ছড়ানো।

In [27]:
arr.std()
# output: 2.581988897471611

np.float64(2.581988897471611)

**.argmax() এবং .argmin() — সর্বোচ্চ ও সর্বনিম্ন মানের index**

.max() মান দেয়, কিন্তু .argmax() দেয় সেই মানটি কোন অবস্থানে আছে।

In [28]:
arr.argmax()
# output: 8 → 9 আছে index 8 এ (flat/1D হিসেবে গণনা করে)



np.int64(8)

In [30]:
arr.argmin()
# output: 0 → 1 আছে index 0 এ

np.int64(0)

2D array তে argmax/argmin flat index দেয় — মানে পুরো array কে 1D ধরে গণনা করে।

# **৬. Reshaping (array এর আকার পরিবর্তন)**

**Reshape কী?**

একটি array এর উপাদান সংখ্যা না বদলে তার আকার পরিবর্তন করা। শর্ত একটাই — আগের এবং পরের উপাদান সংখ্যা সমান হতে হবে।
Syntax: arr.reshape(rows, cols)

In [31]:
arr = np.arange(1, 31)
arr
# output: array([ 1,  2,  3, ..., 30]) → 1D, 30টি উপাদান

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
# 30টি উপাদানকে 6×5 = 30, তাই reshape সম্ভব
arr = arr.reshape(6, 5)

In [34]:
arr
# output:
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25],
#        [26, 27, 28, 29, 30]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**গুরুত্বপূর্ণ নিয়ম:** reshape(6,5) মানে 6×5 = 30 উপাদান। যদি মেলে না, যেমন reshape(4,5) = 20 ≠ 30, তাহলে error আসবে।

# **দ্রুত রিভিশনের জন্য সারসংক্ষেপ**

In [35]:
import pandas as pd

data = {
    "বিষয়": [
        "Array তৈরি",
        "Range array",
        "শূন্য array",
        "এক array",
        "সমান ভাগ",
        "Random 0-1",
        "Random normal",
        "Random int",
        "আকার",
        "মোট উপাদান",
        "ডেটা টাইপ",
        "আকার বদল"
    ],

    "ফাংশন/মেথড": [
        "np.array()",
        "np.arange(start, stop, step)",
        "np.zeros((r,c))",
        "np.ones((r,c))",
        "np.linspace(start, stop, n)",
        "np.random.rand(n)",
        "np.random.randn(n)",
        "np.random.randint(low, high, n)",
        ".shape",
        ".size",
        ".dtype",
        ".reshape(r,c)"
    ],

    "কাজ": [
        "লিস্ট থেকে array",
        "ধাপে ধাপে array",
        "সব 0",
        "সব 1",
        "n টি সমান দূরত্বের মান",
        "Uniform random",
        "Normal distribution",
        "পূর্ণসংখ্যা random",
        "(rows, cols)",
        "সংখ্যা",
        "int64, float64 ইত্যাদি",
        "নতুন আকারে সাজানো"
    ]
}

df = pd.DataFrame(data)

df

,বিষয়,ফাংশন/মেথড,কাজ
0,Array তৈরি,np.array(),লিস্ট থেকে array
1,Range array,"np.arange(start, stop, step)",ধাপে ধাপে array
2,শূন্য array,"np.zeros((r,c))",সব 0
3,এক array,"np.ones((r,c))",সব 1
4,সমান ভাগ,"np.linspace(start, stop, n)",n টি সমান দূরত্বের মান
5,Random 0-1,np.random.rand(n),Uniform random
6,Random normal,np.random.randn(n),Normal distribution
7,Random int,"np.random.randint(low, high, n)",পূর্ণসংখ্যা random
8,আকার,.shape,"(rows, cols)"
9,মোট উপাদান,.size,সংখ্যা
