# **NumPy Array Indexing and Slicing — সম্পূর্ণ নোটস**

**Indexing এবং Slicing কী?**

**Indexing** মানে array এর কোনো নির্দিষ্ট একটি উপাদান বের করা।
**Slicing** মানে array এর একটি অংশ কেটে নেওয়া।

পাইথন লিস্টের মতোই কাজ করে, কিন্তু NumPy তে 2D, 3D array তেও একইভাবে করা যায়।
**Index সবসময় 0 থেকে শুরু হয়** — মানে প্রথম উপাদানের index হলো 0।

**Slicing এর সাধারণ নিয়ম:** `arr[start:stop:step]`


**start** → কোথা থেকে শুরু (অন্তর্ভুক্ত)

**stop** → কোথায় শেষ (অন্তর্ভুক্ত নয়)

**step** → কত করে এগোবে

# **১. Vector (1D Array) এর Indexing ও Slicing**

In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

**Indexing — একটি নির্দিষ্ট উপাদান বের করা**

In [3]:
arr[4]

np.int64(15)

**arr[4]** মানে index 4 এর উপাদান। Index 0 = 11, Index 1 = 12, Index 2 = 13, Index 3 = 14, Index 4 = 15।

**Slicing — অংশ কেটে নেওয়া**

In [4]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

**arr[3::2] মানে:**

3 → index 3 থেকে শুরু (মান 14)

: → শেষ পর্যন্ত যাও

2 → 2 ধাপে এগোও

তাই ফলাফল: [14, 16, 18, 20]

এটা একটা 6 সারি, 5 কলামের matrix। দেখতে এরকম:

       col0  col1  col2  col3  col4
`row0` [  1,    2,    3,    4,    5 ]

`row1` [  6,    7,    8,    9,   10 ]

**row2** [ 11,   12,   13,   14,   15 ]

`row3` [ 16,   17,   18,   19,   20 ]

`row4` [ 21,   22,   23,   24,   25 ]

`row5` [ 26,   27,   28,   29,   30 ]

**2D Slicing — একটি অংশ কেটে নেওয়া**

In [6]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[5]

array([26, 27, 28, 29, 30])

In [9]:
arr[0,4]

np.int64(5)

In [10]:
arr[5,4]

np.int64(30)

In [12]:
slice= arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [13]:
slice_1= arr[3:6,3:5]
slice_1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [14]:
slice_2 = arr[3:,3:]
slice_2

array([[19, 20],
       [24, 25],
       [29, 30]])


**arr[3:, 3:] মানে:**


**সারি:** index 3 থেকে শেষ পর্যন্ত (row3, row4, row5)

**কলাম:** index 3 থেকে শেষ পর্যন্ত (col3, col4)

ফলাফল নিচের ডান কোণের 3×2 অংশ:

[[19, 20],

 [24, 25],

 [29, 30]]

**পুরো একটি কলাম বের করা**

In [15]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**arr[:, 2] মানে:**


: → সব সারি নাও

2 → শুধু index 2 কলাম নাও (col2)


**ফলাফল:** [ 3,  8, 13, 18, 23, 28] — পুরো তৃতীয় কলাম।

একইভাবে পুরো একটি সারি বের করতে হলে: arr[2, :] → তৃতীয় সারি

# **৩. Boolean Indexing — শর্ত দিয়ে ফিল্টার করা**

Boolean Indexing মানে কোনো শর্ত দিলে array থেকে শুধু সেই উপাদানগুলো বের হবে যেগুলো শর্ত পূরণ করে।
তিনটি ধাপে কাজ করে:

1. শর্ত দিয়ে True/False এর array তৈরি করো
2. সেই True/False array দিয়ে মূল array কে filter করো
3. শুধু True অবস্থানের মানগুলো বেরিয়ে আসে

In [16]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

**ধাপ ১ — Boolean Array তৈরি**

In [17]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

প্রতিটি উপাদান জোড় কিনা চেক করছে। জোড় হলে True, বিজোড় হলে False।

ফলাফল: [False, True, False, True, False, True, False, True, False, True]

**ধাপ ২ — Filter করা**

In [18]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

শুধু যেখানে True সেখানকার মান বের হয়।
ফলাফল: [12, 14, 16, 18, 20] — শুধু জোড় সংখ্যাগুলো।


**শর্টকাট:** এই দুটো ধাপ একলাইনেও লেখা যায়: arr[arr % 2 == 0]

# **দ্রুত রিভিশনের জন্য সারসংক্ষেপ**

In [19]:
import pandas as pd

data = {
    "কাজ": [
        "একটি উপাদান",
        "অংশ কাটা",
        "2D একটি উপাদান",
        "2D অংশ কাটা",
        "পুরো কলাম",
        "পুরো সারি",
        "Boolean filter"
    ],

    "Syntax": [
        "arr[i]",
        "arr[start:stop:step]",
        "arr[row, col]",
        "arr[r1:r2, c1:c2]",
        "arr[:, col]",
        "arr[row, :]",
        "arr[শর্ত]"
    ],

    "উদাহরণ": [
        "arr[4] → index 4 এর মান",
        "arr[3::2] → index 3 থেকে, 2 ধাপে",
        "arr[2, 3] → তৃতীয় সারি, চতুর্থ কলাম",
        "arr[3:, 3:] → নিচের ডান অংশ",
        "arr[:, 2] → তৃতীয় কলাম সম্পূর্ণ",
        "arr[2, :] → তৃতীয় সারি সম্পূর্ণ",
        "arr[arr % 2 == 0] → জোড় সংখ্যা"
    ]
}

df = pd.DataFrame(data)

df

,কাজ,Syntax,উদাহরণ
0,একটি উপাদান,arr[i],arr[4] → index 4 এর মান
1,অংশ কাটা,arr[start:stop:step],"arr[3::2] → index 3 থেকে, 2 ধাপে"
2,2D একটি উপাদান,"arr[row, col]","arr[2, 3] → তৃতীয় সারি, চতুর্থ কলাম"
3,2D অংশ কাটা,"arr[r1:r2, c1:c2]","arr[3:, 3:] → নিচের ডান অংশ"
4,পুরো কলাম,"arr[:, col]","arr[:, 2] → তৃতীয় কলাম সম্পূর্ণ"
5,পুরো সারি,"arr[row, :]","arr[2, :] → তৃতীয় সারি সম্পূর্ণ"
6,Boolean filter,arr[শর্ত],arr[arr % 2 == 0] → জোড় সংখ্যা
