# **Array Operations — সম্পূর্ণ নোটস**

#**১. Arithmetic Operations (গাণিতিক অপারেশন)**
NumPy তে দুটো array এর মধ্যে গাণিতিক অপারেশন করলে তা element-wise হয় — মানে একই index এর উপাদানগুলো একে অপরের সাথে হিসাব হয়। পাইথন লিস্টে এটা সরাসরি করা যায় না, NumPy array তেই যায়।

In [1]:
import numpy as np

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

**যোগ — একই index এর উপাদান যোগ হয়:**

In [4]:
arr2= a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

**বিয়োগ:**

In [5]:
arr3=a1 - a2
arr3

array([-5, -5, -5, -5, -5])

**গুণ — element-wise, matrix গুণ নয়:**

In [6]:
arr4= a1 * a2
arr4

array([ 6, 14, 24, 36, 50])

**ভাগ — ফলাফল সবসময় float:**

In [7]:
arr5= a1 / a2
arr5

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

**Floor Division — দশমিক ফেলে দিয়ে পূর্ণসংখ্যা:**

In [8]:
arr6= a1 // a2
arr6

array([0, 0, 0, 0, 0])

**Power — a1 এর প্রতিটি উপাদান a2 এর সমান ঘাতে উঠবে:**

In [9]:
arr7= a1 ** a2
arr7

array([      1,     128,    6561,  262144, 9765625])

**Scalar দিয়ে অপারেশন — Broadcasting এর অংশে বিস্তারিত আছে:**

In [10]:
arr8 = np.arange(1,26).reshape(5,5)
arr8 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# **২. Broadcasting (ব্রডকাস্টিং)**

Broadcasting হলো NumPy এর একটি বিশেষ ক্ষমতা। সাধারণত দুটো array তে অপারেশন করতে হলে তাদের আকার সমান হতে হয়। কিন্তু Broadcasting এর মাধ্যমে **ছোট আকারের array বা একটি সংখ্যাকে** বড় array এর প্রতিটি উপাদানে স্বয়ংক্রিয়ভাবে প্রয়োগ করা যায়।

সহজ কথায় — একটি সংখ্যা দিলে NumPy সেটাকে array এর সব উপাদানে আলাদা আলাদা করে প্রয়োগ করে।

**1D array তে Broadcasting:**

In [11]:
l = [10,20,30,40]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50])

10 কে arr এর প্রতিটি উপাদানে যোগ করা হয়েছে — 10+10, 20+10, 30+10, 40+10।

**2D array তে Broadcasting:**

In [12]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

5×5 matrix এর প্রতিটি উপাদানে 10 যোগ হয়েছে।

# **৩. Deep and Shallow Copy (কপি)**


এটা NumPy এর একটি গুরুত্বপূর্ণ concept। না বুঝলে data হারিয়ে যেতে পারে বা অপ্রত্যাশিত ফলাফল আসতে পারে।

**Shallow Copy (Reference):** নতুন variable তৈরি হয় কিন্তু একই memory তে point করে। একটা বদলালে আরেকটাও বদলায়।

**Deep Copy:** সম্পূর্ণ আলাদা কপি তৈরি হয়। একটা বদলালে আরেকটায় কোনো প্রভাব পড়ে না।

In [14]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

slice = slice * 10 এ নতুন array তৈরি হয়েছে এবং slice এ assign হয়েছে। তাই a অপরিবর্তিত।

**কিন্তু সরাসরি modify করলে মূল array বদলে যেত:**

In [17]:
a[4:6] * 10

array([50, 60])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**.copy() দিয়ে Deep Copy — সম্পূর্ণ আলাদা কপি:**

In [19]:
b = a.copy()

In [21]:
b[0] = 99

In [22]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

b তে 99 দেওয়া হয়েছে কিন্তু a অপরিবর্তিত — কারণ .copy() আলাদা memory তে নতুন array তৈরি করে।

# **৪. Matrix Operations (ম্যাট্রিক্স অপারেশন)**

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
B

array([[5, 6],
       [7, 8]])

**np.dot() — Matrix Multiplication (ম্যাট্রিক্স গুণ)**

`*` দিয়ে গুণ করলে element-wise হয়। কিন্তু গণিতের নিয়মে matrix গুণ করতে হলে np.dot() লাগে।

**Matrix গুণের নিয়ম:** প্রথম matrix এর সারি × দ্বিতীয় matrix এর কলাম।

**A×B এর ফলাফল:**

[1×5 + 2×7,  1×6 + 2×8]   =  [19, 22]

[3×5 + 4×7,  3×6 + 4×8]   =  [43, 50]

In [31]:
A @ B

array([[19, 22],
       [43, 50]])

In [28]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

**`.T` — Transpose (সারি ও কলাম বদলানো)**

Transpose মানে matrix এর সারিগুলো কলাম হয়ে যাবে, কলামগুলো সারি হয়ে যাবে।

In [29]:
A

array([[1, 2],
       [3, 4]])

In [30]:
A.T

array([[1, 3],
       [2, 4]])

A এর প্রথম সারি [1, 2] → A.T এর প্রথম কলাম [1, 2]।

# **৫. Stacking Arrays (array জোড়া লাগানো)**



দুটো বা বেশি array কে একসাথে জোড়া লাগানোকে Stacking বলে। তিনটি উপায় আছে।

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

**`np.vstack()` — Vertical Stack (উপর-নিচে জোড়া)**

a এর নিচে b বসবে — নতুন সারি তৈরি হয়।

In [33]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**`np.hstack()` — Horizontal Stack (পাশাপাশি জোড়া)**
a এর পাশে b বসবে — একটি লম্বা 1D array তৈরি হয়।

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

**`np.column_stack()` — কলাম হিসেবে জোড়া**

প্রতিটি array আলাদা কলাম হয়ে 2D array তৈরি করে।

In [35]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

a প্রথম কলাম, b দ্বিতীয় কলাম।

# **৬. Splitting Arrays (array ভাগ করা)**

Stacking এর উল্টো — একটি array কে একাধিক ভাগে কাটা।

In [36]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**`np.hsplit()`— Horizontal Split (কলাম বরাবর কাটা)**

hsplit(c, 4) মানে 4টি কলামে ভাগ করো — প্রতিটি কলাম আলাদা array হবে।

In [37]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

**`np.vsplit()` — Vertical Split (সারি বরাবর কাটা)**

vsplit(c, 2) মানে 2টি সমান অংশে ভাগ করো — উপরের অর্ধেক ও নিচের অর্ধেক।

In [40]:
a= np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [41]:
for i in a:
  print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# **দ্রুত রিভিশনের জন্য সারসংক্ষেপ**

In [42]:
import pandas as pd

data = {
    "বিষয়": [
        "Element-wise গণিত",
        "Broadcasting",
        "Deep Copy",
        "Matrix গুণ",
        "Transpose",
        "উপর-নিচে জোড়া",
        "পাশাপাশি জোড়া",
        "কলাম জোড়া",
        "কলাম বরাবর কাটা",
        "সারি বরাবর কাটা"
    ],

    "Syntax": [
        "a1 + a2, a1 * a2",
        "arr + 10",
        "b = a.copy()",
        "np.dot(A, B)",
        "A.T",
        "np.vstack((a,b))",
        "np.hstack((a,b))",
        "np.column_stack((a,b))",
        "np.hsplit(arr, n)",
        "np.vsplit(arr, n)"
    ],

    "কাজ": [
        "একই index এর উপাদানে অপারেশন",
        "সংখ্যাটি সব উপাদানে প্রয়োগ হয়",
        "সম্পূর্ণ আলাদা কপি",
        "গাণিতিক matrix multiplication",
        "সারি ↔ কলাম বদলানো",
        "নতুন সারি তৈরি",
        "লম্বা 1D array",
        "প্রতিটি আলাদা কলাম",
        "n টি কলাম অংশে ভাগ",
        "n টি সারি অংশে ভাগ"
    ]
}

df = pd.DataFrame(data)

df

,বিষয়,Syntax,কাজ
0,Element-wise গণিত,"a1 + a2, a1 * a2",একই index এর উপাদানে অপারেশন
1,Broadcasting,arr + 10,সংখ্যাটি সব উপাদানে প্রয়োগ হয়
2,Deep Copy,b = a.copy(),সম্পূর্ণ আলাদা কপি
3,Matrix গুণ,"np.dot(A, B)",গাণিতিক matrix multiplication
4,Transpose,A.T,সারি ↔ কলাম বদলানো
5,উপর-নিচে জোড়া,"np.vstack((a,b))",নতুন সারি তৈরি
6,পাশাপাশি জোড়া,"np.hstack((a,b))",লম্বা 1D array
7,কলাম জোড়া,"np.column_stack((a,b))",প্রতিটি আলাদা কলাম
8,কলাম বরাবর কাটা,"np.hsplit(arr, n)",n টি কলাম অংশে ভাগ
9,সারি বরাবর কাটা,"np.vsplit(arr, n)",n টি সারি অংশে ভাগ
