**Valid Sudoku**

In [1]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

# Sudoku valid kina check korbo

valid = True


# Row check
for row in s:
    if len(np.unique(row)) != 9:
        valid = False

# Column check
for col in s.T:
    if len(np.unique(col)) != 9:
        valid = False


# 3x3 box check
for i in range(0, 9, 3):
    for j in range(0, 9, 3):

        box = s[i:i+3, j:j+3].flatten()

        if len(np.unique(box)) != 9:
            valid = False

# Result
if valid:
    print("Sudoku is Valid")
else:
    print("Sudoku is Invalid")

Sudoku is Valid


**Another Way**

In [2]:
b= np.sum(s,axis=1)
for i in b:
  if i!=45:
    print("For Row It is Invalid")
    break
else:
  print("For Row It is Valid")


For Row It is Valid


In [3]:
b= np.sum(s,axis=0)
for i in b:
  if i!=45:
    print("For Column It is Invalid")
    break
else:
  print("For Column It is Valid")

For Column It is Valid


In [11]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= (s[i:i+3,j:j+3])
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [7]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [8]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

**General Questions**

In [12]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


**1. Get the shape of the matrix**

In [13]:
shape = data.shape

print(shape)

(5, 3)


**2. Find the average age of students**

In [14]:
average_age = np.mean(data[:, 0])

print(average_age)

18.4


**3. Extract Math marks of all students**

In [15]:
math_marks = data[:, 1]

print(math_marks)

[85 92 76 65 90]


**3. Extract Math marks of all students**

In [16]:
math_marks = data[:, 1]

print(math_marks)

[85 92 76 65 90]


**4. Find the highest Science mark**

In [17]:
highest_science = np.max(data[:, 2])

print(highest_science)

95


**5. Get details of the student who scored more than 90 in Math**

In [18]:
students = data[data[:, 1] > 90]

print(students)

[[19 92 88]]


**6. Increase Math marks of all students by 5**

In [19]:
data[:, 1] = data[:, 1] + 5

print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


**7. Find how many students are younger than 19**

In [20]:
count = np.sum(data[:, 0] < 19)

print(count)

3


**8. Calculate the average marks in each subject**

In [21]:
average_subjects = np.mean(data[:, 1:], axis=0)

print(average_subjects)

[86.6 83.2]


**9. Get data of students who scored at least 80 in both subjects**

In [22]:
students = data[
    (data[:, 1] >= 80) &
    (data[:, 2] >= 80)
]

print(students)

[[19 97 88]
 [17 81 95]
 [20 95 85]]


**10. Replace all Science marks < 75 with 0**

In [23]:
data[data[:, 2] < 75, 2] = 0

print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
